### ISSUE TITLE
Fix cla check ci

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/software#1103]

**Comment by Feichtmeier** [comment]
@seb128 could you have a look again? 🙈  It has been failing since some weeks

**Comment by seb128** [comment]
@Feichtmeier could you give some details? Checking the recently open pull requests it's green, picking one example, https://github.com/ubuntu-flutter-community/software/pull/1123

**Comment by Feichtmeier** [comment]
it is since some weeks for commits into main
https://github.com/ubuntu-flutter-community/software/commits/main

I dont't really udnerstand why they pass in the PR but not when merged into main

**Comment by seb128** [comment]
weird, also why are they triggered in that context when the condition is on pull_request_target?

**Comment by d-loose** [comment]
In all commits before https://github.com/ubuntu-flutter-community/software/pull/1034, the CLA check wasn't triggered in the main branch

**Comment by Feichtmeier** [comment]
Yeah I think I was so stupid and added it to required checks for main 
I removed this now. Merged an easy PR by mads - let's see if it is still triggered

**Comment by Feichtmeier** [comment]
yup, still 
![grafik](https://user-images.githubusercontent.com/15329494/221598102-a38122ff-3920-4490-8842-55ce32b2b06f.png)

I don't get it. I thought the required checks for protected branches should not affect pull requests and vice versa

**Comment by Feichtmeier** [comment]
The desktop installer CLA check does not trigger on merge to main
The workflow file looks like this:

```yaml
name: cla-check
on: [pull_request_target]

jobs:
  cla-check:
    if: contains(fromJson('["weblate", "renovate[bot]"]'), github.event.pull_request.user.login) == false
    runs-on: ubuntu-20.04
    steps:
      - name: Check if CLA signed
        uses: canonical/has-signed-canonical-cla@v1
``` 

Wheras our workflow file here looks like this

```yaml
name: cla-check
on: [pull_request_target]

jobs:
  cla-check:
    if: github.event.pull_request.user.login != 'weblate'
    runs-on: ubuntu-20.04
    steps:
      - name: Check if CLA signed
        uses: canonical/has-signed-canonical-cla@v1
```

Eventually the synthax for conditions we use here is wrong? Apart from setting simple values to keys I really don't know much about yaml 😆 I could test this though

The output is also super weird. If there is a pattern than that it passes for canonical employees :D  

```
Run canonical/has-signed-canonical-cla@v1
Installing python3-launchpadlib

Checking the following users on GitHub:
- jpnurmi ✓ (@canonical.com account)
- Feichtmeier ✕ (issue checking CLA status [HttpError: User does not exist or is not a member of the organization])
- d-loose ✓ (@canonical.com account)
- weblate ✕ (issue checking CLA status [HttpError: User does not exist or is not a member of the organization])
- madsrh ✕ (issue checking CLA status [HttpError: User does not exist or is not a member of the organization])

Checking the following users on Launchpad:
- frederik.feichtmeier@gmail.com ✓ (has signed the CLA)
- hosted@weblate.org ✕ (has no Launchpad account)
- madsrh@gmail.com ✓ (has signed the CLA)

Error: CLA Check - FAILED
Posting or updating a comment on the PR
```
